version: '3.7'

services:

    back-end:
        build:
            context: .
            target: app
        volumes:
            - ".:/twitter-dashboard"
        expose:
            - "3000"
        ports:
            - "3002:3000"
        env_file:
            - .env

    cli:
        build:
            context: .
            target: cli
        volumes:
            - ".:/twitter-dashboard" 
        env_file:
            - .env
    
networks:
    default:
        name: twitter-dashboard
    