version: '3.7'

services:

    back-end:
        build:
            context: .
            target: dev-app
            args:
                - PORT=3000
                - NODE_ENV=development
        volumes:
            - ".:/twitter-dashboard"
        ports:
            - "3000:3000"
        stdin_open: true

    cli:
        build:
            context: .
            target: cli
        volumes:
            - ".:/twitter-dashboard" 